name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install npm dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Push to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          package: './package.json'
          registry: 'https://registry.npmjs.org'
          token: ${{secrets.NPM_TOKEN}}